import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "styles/Home.module.css";
import Button from "components/Button";
import GitHub from "components/Icons/GitHub";
import { loginWithGithub } from "firebas/client";
import useUser, { USER_STATUS } from 'hooks/useUser'

export default function Home() {
  const user = useUser();
  const router = useRouter()

  useEffect(() => {
    user && router.replace('/home')
  }, [user])

  const handleClick = () => {
    loginWithGithub().catch((err) => {
        console.log(err);
      });
  };

  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.section} >
        <Image src="/metro.png" alt="Logo" width="400px" height="200px" />
        <h1 className={styles.h1}>Trapter</h1>
        <h2 className={styles.h2}>La red para hablar de Musica</h2>
        <div className={styles.div}>
          {user === USER_STATUS.NOT_LOGGED && (
            <Button onClick={handleClick}>
              <GitHub fill="white" width={32} heigth={24} />
              Login with Github
            </Button>
          )}
          {user === USER_STATUS.NOT_KNOWN && <img src='/spinning-loading.gif' />}
        </div>
      </section>
    </>
  );
}
